name: import-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
  
env:
#edit your values here
  ENVIRONMENT_URL: 'https://epam-rtb-tool-dev.crm4.dynamics.com/'
  CLIENT_ID: '97976641-cbff-4dbd-b6f2-a26270a12e58'
  TENANT_ID: 'b41b72d0-4e9f-4c26-8a69-f949f367c91d'
permissions:
  contents: write
jobs:
  import-to-test:
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1.9.2

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v1.9.2
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v1.9.2
      with:
        solution-folder: solutions/GHActions
        solution-file: solutions/GHActions.zip
        solution-type: Unmanaged
