name: CD

on:
  workflow_dispatch:
    inputs:
      target_environment:
        type: choice
        options:
          - Test
          - Prod
        description: 'Target environment to import the solution to'
        required: true
        default: Test
  
env:
  solution_folder: 'solutions/'
  solution_shipping_folder: 'out/shipping/'
  solution_release_folder: 'out/release/'
  solution_name: 'GHActions'
  solution_exists: false
  solution_version: ''
  
jobs:
  pack-solution:
    name: Pack solution
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v5
      with:
        lfs: true

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1.9.2

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v1.9.2
      with:
        solution-folder: ${{ env.solution_folder }}${{ env.solution_name }}
        solution-file: ${{ env.solution_shipping_folder }}${{ env.solution_name }}_managed.zip
        solution-type: Managed

    - name: Check archive
      run: unzip -l ${{ env.solution_shipping_folder }}${{ env.solution_name }}_managed.zip

    - name: Upload the ready to ship solution to GH artifact store
      uses: actions/upload-artifact@v4
      with:
        name: managedSolutions
        path: ${{ env.solution_shipping_folder }}${{ env.solution_name }}_managed.zip
        overwrite: true
        retention-days: 1


  import-solution:
    name: Import solution to ${{ github.event.inputs.target_environment }} environment
    needs: pack-solution
    environment: ${{ github.event.inputs.target_environment }}
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v5
      with:
        lfs: true

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1.9.2

    - name: Check connection
      uses: microsoft/powerplatform-actions/who-am-i@v1.9.2
      with:
        environment-url: ${{vars.REPO_ENV_PP_URL}}
        app-id: ${{secrets.REPO_ENV_PP_APPID}}
        client-secret: ${{ secrets.REPO_ENV_PP_CLIENTSECRET }}
        tenant-id: ${{secrets.REPO_ENV_PP_TENANTID}}

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v4
      with:
        name: managedSolutions
        path: ${{ env.solution_release_folder }}

    - name: Check archive
      run: unzip -l ${{ env.solution_release_folder }}${{ env.solution_name }}_managed.zip

    - name: Pac auth create
      run: |
        pac auth create \
        --name pacAuthProfile_${{ github.event.inputs.target_environment }} \
        --environment ${{ vars.REPO_ENV_PP_URL }} \
        --tenant ${{ secrets.REPO_ENV_PP_TENANTID }} \
        --applicationId ${{ secrets.REPO_ENV_PP_APPID }} \
        --clientSecret ${{ secrets.REPO_ENV_PP_CLIENTSECRET }}

    - name: Check solution exists
      run: |
        solutions=$(pac solution list --json)

        solutionExists=$(echo "$solutions" |
          jq --arg name "${{ env.solution_name }}" \
          'any(.[]; .SolutionUniqueName == $name)')

        solutionVersion=$(echo "$solutions" |
          jq -r --arg name "${{ env.solution_name }}" \
          '.[] | select(.SolutionUniqueName == $name) | .VersionNumber')

        echo "solution_exists=$solutionExists" >> "$GITHUB_ENV"
        echo "solution_version=$solutionVersion" >> "$GITHUB_ENV"

    - name: Import solution to ${{ github.event.inputs.target_environment }} environment
      uses: microsoft/powerplatform-actions/import-solution@v1.9.2
      with:
        environment-url: ${{vars.REPO_ENV_PP_URL}}
        app-id: ${{secrets.REPO_ENV_PP_APPID}}
        client-secret: ${{ secrets.REPO_ENV_PP_CLIENTSECRET }}
        tenant-id: ${{secrets.REPO_ENV_PP_TENANTID}}
        solution-file: ${{ env.solution_release_folder }}${{ env.solution_name }}_managed.zip
        use-deployment-settings-file: true
        deployment-settings-file: environments/${{ github.event.inputs.target_environment }}/EnvironmentSettings.json
        stage-and-upgrade: ${{ env.solution_exists }}
        force-overwrite: true
        publish-changes: true
        run-asynchronously: true
        max-async-wait-time: 60
