name: My First GitHub Action

# Триггеры: запускать при пуше кода ИЛИ вручную кнопкой на сайте
on:
  #push:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  say-hello-job:
    runs-on: ubuntu-latest # Просим GitHub дать нам сервер на Linux
    
    steps:
      - name: Print welcome message
        run: echo "Привет! Мой первый пайплайн успешно запущен! 🎉"

      - name: Delete artifacts
        shell: pwsh
        run: |
          gh api repos/${{ github.repository }}/actions/artifacts --jq '.total_count'

      - name: Show .NET
        run: |
          dotnet --info
          dotnet --list-sdks
          dotnet --list-runtimes
          
      - name: Which
        run: |
          which dotnet

      - name: Show system information
        run: |
          echo "Текущее время на сервере:"
          date
          echo "Версия операционной системы:"
          lsb_release -a
