name: My First GitHub Action

# Триггеры: запускать при пуше кода ИЛИ вручную кнопкой на сайте
on:
  #push:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

permissions:
  actions: write

jobs:
  say-hello-job:
    runs-on: ubuntu-latest
    environment: Dev
    
    steps:
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1.9.2
        with:
          add-tools-to-path: true      

      - name: Check connection
        uses: microsoft/powerplatform-actions/who-am-i@v1.9.2
        with:
          environment-url: ${{vars.REPO_ENV_PP_URL}}
          app-id: ${{secrets.REPO_ENV_PP_APPID}}
          client-secret: ${{ secrets.REPO_ENV_PP_CLIENTSECRET }}
          tenant-id: ${{secrets.REPO_ENV_PP_TENANTID}}

      - name: List solutions on target environment
        run: |
          pac auth create \
          --name pacAuthProfile_Dev \
          --environment ${{ vars.REPO_ENV_PP_URL }} \
          --tenant ${{ secrets.REPO_ENV_PP_TENANTID }} \
          --applicationId ${{ secrets.REPO_ENV_PP_APPID }} \
          --clientSecret ${{ secrets.REPO_ENV_PP_CLIENTSECRET }}

      - name: List solutions on target environment
        run: pac solution list

      - name: Delete artifacts
        if: false
        shell: pwsh
        run: |
          gh api repos/${{ github.repository }}/actions/artifacts --jq '.total_count'
          $artifacts = gh api repos/${{ github.repository }}/actions/artifacts --paginate --jq '.artifacts[].id'
          foreach ($id in $artifacts) {gh api --method DELETE repos/${{ github.repository }}/actions/artifacts/$id}
