name: My First GitHub Action

on:
  #push:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}
  solution_name: 'GHActions'
  solution_exists: false

permissions:
  actions: write

jobs:
  say-hello-job:
    runs-on: ubuntu-latest
    environment: Dev
    
    steps:
      - name: Check if solution already exists in environment
        shell: pwsh
        run: |
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          Install-Module -Scope CurrentUser -Name Microsoft.Xrm.Data.Powershell -AllowClobber -Force
          $module = Get-Module -ListAvailable Microsoft.Xrm.Data.Powershell | Select-Object -First 1
          Import-Module $module.Path

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1.9.2
        with:
          add-tools-to-path: true      

      - name: Check connection
        if: false
        uses: microsoft/powerplatform-actions/who-am-i@v1.9.2
        with:
          environment-url: ${{vars.REPO_ENV_PP_URL}}
          app-id: ${{secrets.REPO_ENV_PP_APPID}}
          client-secret: ${{ secrets.REPO_ENV_PP_CLIENTSECRET }}
          tenant-id: ${{secrets.REPO_ENV_PP_TENANTID}}

      - name: Pac auth create
        run: |
          pac auth create \
          --name pacAuthProfile_Dev \
          --environment ${{ vars.REPO_ENV_PP_URL }} \
          --tenant ${{ secrets.REPO_ENV_PP_TENANTID }} \
          --applicationId ${{ secrets.REPO_ENV_PP_APPID }} \
          --clientSecret ${{ secrets.REPO_ENV_PP_CLIENTSECRET }}

      - name: List solutions on target environment
        run: pac solution list --json | jq

      - name: List solutions on target environment
        if: true
        run: |
          solutionExists=$(
          pac solution list --json |
          jq --arg name ${{ env.solution_name }} \
          'any(.[]; .SolutionUniqueName == $name)'
          )
          echo "solution_exists=$solutionExists" >> "$GITHUB_ENV"

      - name: Print result
        run: echo "${{ env.solution_exists }}"

      - name: Delete artifacts
        if: false
        shell: pwsh
        run: |
          gh api repos/${{ github.repository }}/actions/artifacts --jq '.total_count'
          $artifacts = gh api repos/${{ github.repository }}/actions/artifacts --paginate --jq '.artifacts[].id'
          foreach ($id in $artifacts) {gh api --method DELETE repos/${{ github.repository }}/actions/artifacts/$id}
